import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(home)/_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "viserlab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
