import Footer from "./_components/Footer/Footer";

export const metadata = {
  title: "viserlab",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
